apiVersion: v2
name: yet-another-cloudwatch-exporter
description: Yace - Yet Another CloudWatch Exporter
type: application
version: 0.2.0
appVersion: "v0.51.0"
home: https://github.com/nerdswords/helm-charts
sources:
- https://github.com/nerdswords/yet-another-cloudwatch-exporter
keywords:
- aws
- cloudwatch
- prometheus
- exporter
- yet-another-cloudwatch-exporter
- yace
